name: backend_alex
description: Servidor backend en Dart con Shelf y WebSocket
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.1
  shelf_web_socket: ^1.0.3
  web_socket_channel: ^2.4.0

dev_dependencies:
  lints: ^3.0.0
